const ESTADOS_VEHICULO = {
  EN_TERMINAL: 1,
  EN_RUTA: 2,
  PROXIMO: 3,
};

const ESTADOS_CONDUCTOR = {
  DISPONIBLE: 1,
  EN_VIAJE: 2,
  INACTIVO: 3,
};

const ESTADOS_VIAJE = {
  BUSCANDO: 1,
  ACEPTADO: 2,
  EN_CURSO: 3,
  FINALIZADO: 4,
  CANCELADO: 5,
};

const TRANSICIONES_VIAJE = {
  [ESTADOS_VIAJE.BUSCANDO]: [ESTADOS_VIAJE.ACEPTADO, ESTADOS_VIAJE.CANCELADO],
  [ESTADOS_VIAJE.ACEPTADO]: [ESTADOS_VIAJE.EN_CURSO, ESTADOS_VIAJE.CANCELADO],
  [ESTADOS_VIAJE.EN_CURSO]: [ESTADOS_VIAJE.FINALIZADO, ESTADOS_VIAJE.CANCELADO],
  [ESTADOS_VIAJE.FINALIZADO]: [],
  [ESTADOS_VIAJE.CANCELADO]: [],
};

module.exports = { ESTADOS_VEHICULO, ESTADOS_CONDUCTOR, ESTADOS_VIAJE, TRANSICIONES_VIAJE };
