name: Deploy Backend RutaGo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.PASSWORD_SSH }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER_NAME_RUTA_GO }}@${{ secrets.HOST }} <<EOF
            set -e

            echo "Desplegando RutaGo Backend..."

            cd /home/${{ secrets.USER_NAME_RUTA_GO }}/backend

            echo "→ git pull..."
            git pull origin main

            echo "→ npm install..."
            npm install --omit=dev

            echo "→ db:migrate..."
            npx sequelize-cli db:migrate

            echo "→ Reiniciando servicio..."
            sudo systemctl restart rutago.service

            echo "→ Estado del servicio:"
            sudo systemctl status rutago.service --no-pager

            echo "✅ Deploy finalizado."
          EOF
