name: Deploy Backend Express

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Compress project files
        run: |
          mkdir ../build_tmp
          cp -r . ../build_tmp/
          rm -rf ../build_tmp/.git ../build_tmp/node_modules
          tar -czf backend.tar.gz -C ../build_tmp .
          rm -rf ../build_tmp
          
      - name: Upload and Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME_RUTA_GO }}
          key: ${{ secrets.PASSWORD_SSH }}
          port: 22
          script_stop: true # Detiene el proceso si algún comando falla
          script: |
            # Crear la carpeta si no existe y entrar
            mkdir -p ~/backend
            cd ~/backend
            
            # Limpiar contenido viejo antes de extraer el nuevo (excepto el archivo tar que va llegando)
            find . -maxdepth 1 ! -name '.' ! -name 'backend.tar.gz' -exec rm -rf {} +

      - name: Transfer Compressed File
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME_RUTA_GO }}
          key: ${{ secrets.PASSWORD_SSH }}
          port: 22
          source: "backend.tar.gz"
          target: "/home/${{ secrets.USER_NAME_RUTA_GO }}/backend/"

      - name: Extract and Start Backend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME_RUTA_GO }}
          key: ${{ secrets.PASSWORD_SSH }}
          port: 22
          script: |
            cd ~/backend
            tar -xzf backend.tar.gz
            rm backend.tar.gz
            
            # Instalar dependencias limpias en producción
            npm install --production
            
            # Inicializar Base de Datos
            HOST="${{ secrets.HOST }}" \
            USER_DB="${{ secrets.USER_DB }}" \
            DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
            DB_NAME="${{ secrets.DB_NAME }}" \
            node init-db.js
            
            # Manejo de PM2 con npx para evitar fallos de comando no encontrado
            PORT=8082 \
            HOST="${{ secrets.HOST }}" \
            USER_DB="${{ secrets.USER_DB }}" \
            DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
            DB_NAME="${{ secrets.DB_NAME }}" \
            npx pm2 restart express-back || \
            PORT=8082 \
            HOST="${{ secrets.HOST }}" \
            USER_DB="${{ secrets.USER_DB }}" \
            DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
            DB_NAME="${{ secrets.DB_NAME }}" \
            npx pm2 start index.js --name "express-back"
